//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomaticMailPrinter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutomaticMailPrinter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutomaticMailPrinter.
        /// </summary>
        public static string strAppTitle {
            get {
                return ResourceManager.GetString("strAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection success!.
        /// </summary>
        public static string strConnectionEstablishedSuccess {
            get {
                return ResourceManager.GetString("strConnectionEstablishedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to the mail-server {0} ....
        /// </summary>
        public static string strConnectToMailServer {
            get {
                return ResourceManager.GetString("strConnectToMailServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0} messages from inbox!.
        /// </summary>
        public static string strDeleteNMessagesFromInBox {
            get {
                return ResourceManager.GetString("strDeleteNMessagesFromInBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete old messages from inbox ....
        /// </summary>
        public static string strDeleteOldMessagesFromInBox {
            get {
                return ResourceManager.GetString("strDeleteOldMessagesFromInBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string strError {
            get {
                return ResourceManager.GetString("strError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flush e-mails marked as deleted (Expunge) ....
        /// </summary>
        public static string strExpungeMails {
            get {
                return ResourceManager.GetString("strExpungeMails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        public static string strFailedToConnect {
            get {
                return ResourceManager.GetString("strFailedToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to play the sound.
        /// </summary>
        public static string strFailedToPlaySound {
            get {
                return ResourceManager.GetString("strFailedToPlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to print mail.
        /// </summary>
        public static string strFailedToPrintMail {
            get {
                return ResourceManager.GetString("strFailedToPrintMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faild to read config file.
        /// </summary>
        public static string strFailedToReadConfigFile {
            get {
                return ResourceManager.GetString("strFailedToReadConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to recieve mails.
        /// </summary>
        public static string strFailedToRecieveMails {
            get {
                return ResourceManager.GetString("strFailedToRecieveMails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found unread mail with filter (&quot;{0}&quot;):.
        /// </summary>
        public static string strFoundUnreadMail {
            get {
                return ResourceManager.GetString("strFoundUnreadMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance already running!.
        /// </summary>
        public static string strInstanceAlreadyRunning {
            get {
                return ResourceManager.GetString("strInstanceAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy HH:mm:ss.fff.
        /// </summary>
        public static string strLogFormat {
            get {
                return ResourceManager.GetString("strLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for unread mails ....
        /// </summary>
        public static string strLookingForUnreadMails {
            get {
                return ResourceManager.GetString("strLookingForUnreadMails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mail client is not connect anymore. Reconnecting ....
        /// </summary>
        public static string strMailClientIsNotConnectedAnymore {
            get {
                return ResourceManager.GetString("strMailClientIsNotConnectedAnymore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark mail as deleted ....
        /// </summary>
        public static string strMarkMailAsDeleted {
            get {
                return ResourceManager.GetString("strMarkMailAsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark mail as read ....
        /// </summary>
        public static string strMarkMailAsRead {
            get {
                return ResourceManager.GetString("strMarkMailAsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No unread messages found!.
        /// </summary>
        public static string strNoUnreadMailFound {
            get {
                return ResourceManager.GetString("strNoUnreadMailFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing mail &quot;{0}&quot; with {1} ....
        /// </summary>
        public static string strPrintMessage {
            get {
                return ResourceManager.GetString("strPrintMessage", resourceCulture);
            }
        }
    }
}
